=== FabioCosentUni/telepass/src/main/resources/xsd/Autostrade.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">


    <xs:element name="autostrade">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="autostrada" type="autostrada" maxOccurs="unbounded" minOccurs="0"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:complexType name="autostrada">
        <xs:sequence>
            <xs:element name="tariffario" type="tariffario" maxOccurs="1"/>
        </xs:sequence>
        <xs:attribute name="nome" type="xs:string" use="required"/>
    </xs:complexType>


    <xs:complexType name="tariffario">
        <xs:sequence>
            <xs:element name="classe" type="classe"  maxOccurs="unbounded">
            </xs:element>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="classe">
        <xs:simpleContent>
            <xs:extension base="xs:decimal">
                <xs:attribute name="nome" type="xs:string" use="required"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>


</xs:schema>

=== FabioCosentUni/telepass/src/main/resources/xml/Autostrade.xml
<?xml version="1.0" encoding="UTF-8"?>
<autostrade xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
            xsi:noNamespaceSchemaLocation="../xsd/Autostrade.xsd">
    <autostrada nome="A1">
        <tariffario>
            <classe nome="A">0.1</classe>
            <classe nome="B">0.2</classe>
            <classe nome="C">0.3</classe>
            <classe nome="3">0.2</classe>
            <classe nome="4">0.2</classe>
            <classe nome="5">0.4</classe>
        </tariffario>
    </autostrada>
    <autostrada nome="A24">
        <tariffario>
            <classe nome="A">0.1</classe>
            <classe nome="B">0.2</classe>
            <classe nome="C">0.3</classe>
            <classe nome="3">0.2</classe>
            <classe nome="4">0.2</classe>
            <classe nome="5">0.4</classe>
        </tariffario>
    </autostrada>
    <autostrada nome="A25">
        <tariffario>
            <classe nome="A">0.1</classe>
            <classe nome="B">0.2</classe>
            <classe nome="C">0.3</classe>
            <classe nome="3">0.2</classe>
            <classe nome="4">0.2</classe>
            <classe nome="5">0.4</classe>
        </tariffario>
    </autostrada>
    <autostrada nome="A5">
        <tariffario>
            <classe nome="A">0.1</classe>
            <classe nome="B">0.2</classe>
            <classe nome="C">0.3</classe>
            <classe nome="3">0.2</classe>
            <classe nome="4">0.2</classe>
            <classe nome="5">0.4</classe>
        </tariffario>
    </autostrada>
    <autostrada nome="A11">
        <tariffario>
            <classe nome="A">0.1</classe>
            <classe nome="B">0.2</classe>
            <classe nome="C">0.3</classe>
            <classe nome="3">0.2</classe>
            <classe nome="4">0.2</classe>
            <classe nome="5">0.4</classe>
        </tariffario>
    </autostrada>
    <autostrada nome="A12">
        <tariffario>
            <classe nome="A">0.1</classe>
            <classe nome="B">0.2</classe>
            <classe nome="C">0.3</classe>
            <classe nome="3">0.2</classe>
            <classe nome="4">0.2</classe>
            <classe nome="5">0.4</classe>
        </tariffario>
    </autostrada>
    <autostrada nome="A13">
        <tariffario>
            <classe nome="A">0.1</classe>
            <classe nome="B">0.2</classe>
            <classe nome="C">0.3</classe>
            <classe nome="3">0.2</classe>
            <classe nome="4">0.2</classe>
            <classe nome="5">0.4</classe>
        </tariffario>
    </autostrada>

</autostrade>
